name: Integração Contínua

on:
  push:
  pull_request:

jobs:
  qualidade:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4
      
      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Executar Limpeza
        run: mvn clean
        
      - name: Executar testes
        run: mvn test